# /docker-compose.yml - Versão Final Simplificada
# version: '3.8'
services:
  backend:
    build:
      context: ./fastapi_backend
    container_name: setormusicalms-backend
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
  frontend:
    build:
      context: ./frontend
    container_name: setormusicalms-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - app-network
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: setormusicalms-nginx-proxy
    ports:
      - "8001:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network
volumes:
  sqlite_data:
    driver: local
networks:
  app-network:
    driver: bridge
