# docker-compose.yml
# Versão 11 - 29/07/2025 05:30 - Alinha os contextos de build e remove comandos sobrepostos

services:
  backend:
    build:
      context: ./fastapi_backend
    container_name: setormusicalms-backend
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: setormusicalms-frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped

  nginx-proxy:
    build:
      context: .
      dockerfile: nginx-proxy.Dockerfile # Usando um Dockerfile específico para o proxy
    container_name: setormusicalms-nginx-proxy
    ports:
      - "8001:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
