# docker-compose.yml
# Versão 114 - Final, Corrigida e Otimizada para Produção

services:
  # --- SERVIÇO DE BACKEND (FastAPI) ---
  # Nenhuma alteração necessária aqui.
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    expose:
      - "8000"
    restart: unless-stopped

  # --- SERVIÇO DE FRONTEND (Next.js) ---
  # A única alteração é a remoção da linha 'command'.
  # O novo Dockerfile do frontend agora gerencia como a aplicação é iniciada.
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    # A linha 'command' foi REMOVIDA daqui.
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped

  # --- SERVIÇO DE PROXY REVERSO (Nginx) ---
  # Nenhuma alteração necessária aqui.
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: setormusicalms-nginx-proxy
    ports:
      # Expõe a porta 80 do proxy para a porta 8001 da VPS.
      - "8001:80"
    volumes:
      # Monta o arquivo de configuração do Nginx.
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

# --- VOLUME PERSISTENTE PARA O BANCO DE DADOS ---
# Garante que os dados do SQLite não sejam perdidos ao recriar o contêiner do backend.
volumes:
  sqlite_data:
