# docker-compose.yml
# Versão 65 - Padronizado para a porta 8001

services:
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    ports:
      # CORREÇÃO FINAL: Mapeia a porta 8001 do host (VPS) para a nova porta 8001 do contêiner.
      - "8001:8001"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
