# docker-compose.yml (versão completa e corrigida)

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    build: ./backend
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8000:8000"

# --- SECÇÃO IMPORTANTE ---
# Certifique-se de que esta secção existe no final do seu ficheiro.
volumes:
  postgres_data:
  static_volume:
  media_volume:
