# docker-compose.yml 

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # As variáveis são definidas diretamente aqui
    environment:
      POSTGRES_DB: setormusicalms_db
      POSTGRES_USER: mestre
      POSTGRES_PASSWORD: Setor@MS25 # Use a sua senha real aqui
    restart: always

  backend:
    build: ./backend
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    # As variáveis são definidas diretamente aqui
    environment:
      # Configurações do Django
      SECRET_KEY: 05&4v2cr133p0qq)4a*d$e*40n1-rwyf6ol8ghe3o%p2-lm1us # Use a sua chave real
      DEBUG: 0
      ALLOWED_HOSTS: localhost,127.0.0.1,setormusicalms.art.br
      CORS_ALLOWED_ORIGINS: https://setormusicalms.art.br,http://setormusicalms.art.br,http://localhost
      
      # Configurações do Banco de Dados
      POSTGRES_DB: setormusicalms_db
      POSTGRES_USER: mestre
      POSTGRES_PASSWORD: Setor@MS25 # Use a sua senha real aqui
      SQL_HOST: db
      SQL_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:
