# /home/setormusicalms/setormusicalms/docker-compose.yml
# Versão Final Corrigida - 25/07/2025

services:
  backend:
    image: ghcr.io/rnetmail/setormusicalms-backend:latest
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - sqlite_data:/app/data
    # Expõe a porta para o Nginx da VPS que não está em contêiner
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/rnetmail/setormusicalms-frontend:latest
    container_name: setormusicalms-frontend
    # Expõe a porta 3000 interna para a porta 8001 da VPS, que o Nginx externo espera
    ports:
      - "8001:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
