# docker-compose.yml
# Versão 60 19/07/2025 19:00
services:
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      # O backend expõe a porta 8000, conforme esperado pelo Nginx.
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    ports:
      # CORREÇÃO: Mapeia a porta 80 do contentor para a porta 3000 do host,
      # alinhando-se com a regra 'proxy_pass' do Nginx da VPS.
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
