# /docker-compose.yml
# Versão 01 25/07/2025 17:20
services:
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped

  frontend:
    build: .
    container_name: setormusicalms-frontend
    ports:
      # A porta interna 80 do Nginx será mapeada para a 8001 da VPS
      - "8001:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
