# docker-compose.yml

services:
  backend:
    # Usa a imagem do registro em produção, com fallback para build local
    image: ${IMAGE_NAME_BACKEND:-setormusicalms-backend-local}
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_db:/app/data
    env_file:
      - .env

  frontend:
    # Usa a imagem do registro em produção, com fallback para build local
    image: ${IMAGE_NAME_FRONTEND:-setormusicalms-frontend-local}
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  sqlite_db:


