# docker-compose.yml
# Versão 52 19/07/2025 13:50

services:
  # Serviço do Backend FastAPI
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    # CORREÇÃO FINAL: Define explicitamente a variável de ambiente DENTRO da
    # configuração do serviço. Isto garante que o contentor SEMPRE usará
    # o SQLite, ignorando quaisquer variáveis externas que possam existir.
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped

  # Serviço do Frontend (React) servido pelo Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
