# docker-compose.test.yml
# version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./tests:/tests
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:///data/test.db
      - SECRET_KEY=testkey
    command: ["pytest", "--maxfail=2", "--disable-warnings", "--tb=short", "-v"]
    networks:
      - testnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - testnet
    depends_on:
      - backend
    command: ["npm", "run", "preview"]  # Vite preview server
    ports:
      - "4173:4173"  # Porta usada por Vite preview

  e2e:
    image: mcr.microsoft.com/playwright:v1.43.1-jammy
    working_dir: /tests-e2e
    volumes:
      - ./tests-e2e:/tests-e2e
    depends_on:
      - frontend
    entrypoint: ["npx", "playwright", "test", "--project=chromium"]
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
