# /docker-compose.yml
# v4.0 - 2025-08-06 17:40:00 - Corrige health check e simplifica dependências.

services:
  backend:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-uma-chave-secreta-forte-e-dificil-de-adivinhar}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-10080}
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
