services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod  # <-- ALTERADO
    restart: always

  backend:
    build: ./backend
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    env_file:
      - ./.env.prod  # <-- ALTERADO
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:
