# /docker-compose.yml - Adicionando PYTHONPATH
version: '3.8'

services:
  backend:
    build:
      context: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - sqlite_data:/app/data
    environment:
      # LINHA ESSENCIAL PARA AS IMPORTAÇÕES FUNCIONAREM
      - PYTHONPATH=/app 
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  # ... (resto do arquivo sem alterações ) ...
  frontend:
    build:
      context: ./frontend
    container_name: setormusicalms-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - app-network

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: setormusicalms-nginx-proxy
    ports:
      - "8001:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  sqlite_data:
    driver: local

networks:
  app-network:
    driver: bridge
