# /docker-compose.yml - Versão Final e Definitiva
# version: '3.8'

services:
  backend:
    # Usa a imagem construída pelo CI/CD, que contém o código correto.
    image: ghcr.io/rnetmail/setormusicalms-backend:latest
    container_name: setormusicalms-backend
    # O comando já está correto para a estrutura simplificada.
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      # --- A CORREÇÃO CRUCIAL ESTÁ AQUI ---
      # REMOVEMOS a linha que montava o código local: '- ./fastapi_backend:/app'
      # Mantemos apenas o volume para persistir o banco de dados.
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - app-network
    healthcheck:
      # O health check agora aponta para a raiz, que é mais simples e confiável.
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    # Usa a imagem construída pelo CI/CD.
    image: ghcr.io/rnetmail/setormusicalms-frontend:latest
    container_name: setormusicalms-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - app-network

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: setormusicalms-nginx-proxy
    ports:
      - "8001:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
        depends_on:
      backend:
         # Agora o healthcheck é crucial e confiável.
    restart: unless-stopped
    networks:
      - app-network

volumes:
  sqlite_data:
    driver: local

networks:
  app-network:
    driver: bridge
