# docker-compose.yml
# Versão 45 18/07/2025 11:30
services:
  # Serviço do Backend FastAPI
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    # Em produção, o --reload é removido para melhor performance e estabilidade.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      # O volume do código é mantido para facilitar o debug, mas pode ser removido
      # se a imagem já contiver a versão final do código.
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    environment:
      # Em produção, estes valores seriam idealmente geridos por um sistema de segredos.
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped

  # Serviço do Frontend (React) servido pelo Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    ports:
      # CORREÇÃO CRÍTICA: Mapeia a porta 3000 do host para a porta 80 do contentor,
      # que é a porta onde o Nginx está a escutar.
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
