services:
  backend:
    build: ./backend
    container_name: setormusicalms_backend_sqlite
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # As variáveis de ambiente do banco de dados já não são necessárias aqui

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms_frontend_nginx
    ports:
      - "8001:80"
    depends_on:
      - backend # Agora depende diretamente do backend
    restart: unless-stopped
