# docker-compose.yml
# Versão 49 19/07/2025 13:30

services:
  # Serviço do Backend FastAPI
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      # O backend continua a expor a porta 8000 para a API
      - "8000:8000"
    restart: unless-stopped

  # Serviço do Frontend (React) servido pelo Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    ports:
      # CORREÇÃO: Mapeia a porta 80 do host para a porta 80 do contentor.
      # Isto permite que o Nginx automatizado da VPS encontre a aplicação
      # diretamente na porta padrão de HTTP.
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
