# docker-compose.yml
# Versão 53 19/07/2025 18:30
services:
  # Serviço do Backend FastAPI
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      # Expõe a porta 8000 para a API
      - "8000:8000"
    environment:
      # Força o uso do SQLite, sobrescrevendo qualquer variável externa.
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped

  # Serviço do Frontend (React) servido pelo Nginx
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    ports:
      # CORREÇÃO: Mapeia a porta 80 do host para a porta 80 do contentor.
      # O Nginx automatizado da VPS irá procurar a aplicação nesta porta.
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
