# docker-compose.yml (VERSÃO FINAL PARA DEPLOY)

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: setormusicalms_db
      POSTGRES_USER: mestre # Use o seu user real
      POSTGRES_PASSWORD: Setor@MS25 # Use a sua senha real
    restart: always

  # Serviço do Backend (Django)
  backend:
    build: ./backend
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    environment:
      SECRET_KEY: sua-chave-secreta-super-forte-aqui # Use a sua chave real
      DEBUG: 0
      ALLOWED_HOSTS: "*" # Permite todos os hosts, seguro pois não está exposto publicamente
      POSTGRES_DB: setormusicalms_db
      POSTGRES_USER: mestre # Use o seu user real
      POSTGRES_PASSWORD: Setor@MS25 # Use a sua senha real
      SQL_HOST: db
      SQL_PORT: 5432
    # NENHUMA porta exposta para o público. Apenas o Nginx fala com ele.

  # Serviço do Frontend (O nosso Nginx)
  frontend:
    # Constrói a imagem a partir do Dockerfile que criámos na raiz
    build: .
    ports:
      # Mapeia a porta 8001 da VPS para a porta 80 do nosso contentor Nginx
      - "8001:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
