// docker-compose.yml
// Versão 63 22/07/2025 20:51
services:
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      # Expõe a porta 8000 do backend para o host
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    ports:
      # Mapeia a porta 8001 do host para a porta 8001 do contêiner
      - "8001:8001"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
