# docker-compose.yml
# Versão 67 18/07/2025 08:15

# version: '3.8'

services:
  # Serviço do Backend FastAPI
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms_fastapi_backend_sqlite
    # CORREÇÃO: Comando de arranque estável, sem '--reload'.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      # Mapeia o código local para dentro do contentor
      - ./fastapi_backend:/app
      # CORREÇÃO: Volume para persistir o banco de dados SQLite
      - sqlite_data:/app/data
    ports:
      # Expõe a porta 8000 do contentor na porta 8001 do anfitrião (VPS).
      - "8001:8000"
    environment:
      # CORREÇÃO: Aponta para o caminho do ficheiro SQLite dentro do contentor.
      - DATABASE_URL=sqlite:///data/setormusical.db
      - SECRET_KEY=sua-chave-secreta-super-forte-aqui
      - ALGORITHM=HS256
    restart: unless-stopped

  # Serviço do Frontend com Nginx como servidor web
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms_react_frontend
    ports:
      # Expõe a porta 80 do contentor na porta 80 do anfitrião (VPS).
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

# Definição do volume para persistência do banco de dados SQLite
volumes:
  sqlite_data:
