# docker-compose.yml

services:
  backend:
    build: ./backend
    container_name: setormusicalms_backend_sqlite
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      # CORREÇÃO: O contexto de build é a pasta atual ('.')
      # onde o Dockerfile principal se encontra.
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms_frontend_nginx
    ports:
      - "8001:80"
    depends_on:
      - backend
    restart: unless-stopped
