// docker-compose.yml
// Versão 64 22/07/2025 21:05
services:
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi_backend:/app
      - sqlite_data:/app/data
    ports:
      # A porta 8000 é exposta apenas para a rede interna do Docker, não para o host
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    restart: unless-stopped

  nginx:
    # O serviço nginx agora constrói a partir do Dockerfile principal
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-nginx-proxy
    ports:
      # Mapeia a porta 8001 do host para a porta 80 do nosso Nginx
      - "8001:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
