# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env # Adicione esta linha para carregar as variáveis do arquivo .env
    volumes:
      - sqlite_db:/app/data
