# docker-compose.yml
# Versão 113 - Final com Proxy Interno

services:
  backend:
    build: ./fastapi_backend
    container_name: setormusicalms-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///data/setormusical.db
    # Não expõe mais a porta para o host, a comunicação é interna.
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setormusicalms-frontend
    # Não expõe mais a porta para o host.
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: setormusicalms-nginx-proxy
    ports:
      # Expõe a porta 80 do proxy para a porta 8001 da VPS, que o Nginx externo espera.
      - "8001:80"
    volumes:
      # Monta o nosso novo arquivo de configuração dentro do contêiner.
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  sqlite_data:
