version: '3.8'

services:
  fastapi-backend:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://mestre:Setor@MS25@db:5432/setormusicalms_db
      - SECRET_KEY=sua-chave-secreta-super-forte-aqui-fastapi
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - setormusicalms_default

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: setormusicalms_db
      POSTGRES_USER: mestre
      POSTGRES_PASSWORD: Setor@MS25
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - setormusicalms_default

volumes:
  postgres_data:

networks:
  setormusicalms_default:
    external: true
